#!/usr/bin/env bash
# infra/phase6-crm/up.sh — Phase 6: build + deploy the RM cockpit dashboard.
set -euo pipefail
PHASE="phase6"; export PHASE
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../common/env.sh
source "$SCRIPT_DIR/../common/env.sh"

log "Phase 6 — CRM dashboard (RM cockpit)"
ensure_az_login
ensure_rg

PHASE1_OUT="$SCRIPT_DIR/../phase1-platform/outputs.env"
PHASE4_OUT="$SCRIPT_DIR/../phase4-toolapi/outputs.env"
for f in "$PHASE1_OUT" "$PHASE4_OUT"; do
  [[ -f "$f" ]] || die "Missing outputs: $f (run that phase first)"
  # shellcheck disable=SC1090
  source "$f"
done
[[ -n "${ACR_LOGIN_SERVER:-}" && -n "${UAMI_ID:-}" && -n "${TOOLAPI_URL:-}" && -n "${TOOLAPI_BEARER_TOKEN:-}" ]] || die "Incomplete prior outputs (need ACR_LOGIN_SERVER, UAMI_ID, TOOLAPI_URL, TOOLAPI_BEARER_TOKEN)."
ok "Loaded phase 1 + 4 outputs (TOOLAPI_URL=$TOOLAPI_URL)"

# Video Assist URL (Step 7 video call) from phase9, if it has run. Optional — the
# dashboard still deploys without it; the Step 7 button shows a friendly message.
PHASE9_OUT="$SCRIPT_DIR/../phase9-videoassist/outputs.env"
if [[ -f "$PHASE9_OUT" ]]; then
  # shellcheck disable=SC1090
  source "$PHASE9_OUT"
  ok "Loaded phase 9 output (VIDEOASSIST_URL=${VIDEOASSIST_URL:-unset})"
else
  warn "phase9 outputs not found — Step 7 video-call URL will be empty until phase9 runs."
fi

# Build image (uses ACR base-image cache rule if present, else Docker Hub) — or reuse
# an image built in parallel by infra/common/prebuild_images.sh during phase2.
IMAGE_REPO="msme-dashboard"
PREBUILT_ENV="$SCRIPT_DIR/../common/prebuilt_images.env"
[[ -f "$PREBUILT_ENV" ]] && source "$PREBUILT_ENV"
if [[ -n "${PREBUILT_DASHBOARD_IMAGE:-}" ]]; then
  IMAGE_REF="$PREBUILT_DASHBOARD_IMAGE"
  ok "Reusing pre-built dashboard image (built in parallel during phase2): $IMAGE_REF"
else
  IMAGE_TAG="v$(date -u +%Y%m%d%H%M%S)"
  IMAGE_REF="${ACR_LOGIN_SERVER}/${IMAGE_REPO}:${IMAGE_TAG}"
  log "Building dashboard image: $IMAGE_REF"
  az acr build --registry "$NAME_ACR" \
    --image "${IMAGE_REPO}:${IMAGE_TAG}" --image "${IMAGE_REPO}:latest" \
    --build-arg BASE_REGISTRY="${ACR_LOGIN_SERVER}/" \
    --file "$REPO_ROOT/frontend-crm/Dockerfile" "$REPO_ROOT" --only-show-errors \
    || { warn "ACR-cache base build failed; retrying via Docker Hub base"; \
         az acr build --registry "$NAME_ACR" \
           --image "${IMAGE_REPO}:${IMAGE_TAG}" --image "${IMAGE_REPO}:latest" \
           --file "$REPO_ROOT/frontend-crm/Dockerfile" "$REPO_ROOT" --only-show-errors; }
  ok "Image built"
fi

DEPLOYMENT_NAME="phase6-crm-$(date -u +%Y%m%d-%H%M%S)"
log "Deploying dashboard Container App..."
az deployment group create -g "$AZ_RG" -n "$DEPLOYMENT_NAME" \
  --template-file "$SCRIPT_DIR/main.bicep" \
  --parameters location="$AZ_REGION" projectTag="$PROJECT_TAG_VALUE" \
      acaEnvName="$NAME_ACA_ENV" acrName="$NAME_ACR" appName="$NAME_CA_CRM" \
      imageRef="$IMAGE_REF" uamiResourceId="$UAMI_ID" \
      toolapiBearerToken="$TOOLAPI_BEARER_TOKEN" \
      toolapiUrl="$TOOLAPI_URL" videoassistUrl="${VIDEOASSIST_URL:-}" \
  --only-show-errors -o table
ok "Dashboard deployed"

DASH_URL="$(az deployment group show -g "$AZ_RG" -n "$DEPLOYMENT_NAME" --query properties.outputs.appUrl.value -o tsv)"
cat > "$SCRIPT_DIR/outputs.env" <<EOF2
# Generated by infra/phase6-crm/up.sh on $(date -u --iso-8601=seconds)
export DASHBOARD_URL="$DASH_URL"
export DASH_URL="$DASH_URL"
export DASHBOARD_IMAGE="$IMAGE_REF"
EOF2

log "Smoke-testing dashboard /healthz ..."
for i in $(seq 1 15); do
  curl -fsS "$DASH_URL/healthz" >/dev/null 2>&1 && { ok "Dashboard healthy"; break; }
  [[ $i -eq 15 ]] && warn "Health not confirmed yet (may still be starting)."
  sleep 5
done

cat <<EOF3

$(printf '\033[1;36m================ Phase 6 — Deployed ================\033[0m')
  Dashboard URL:  $DASH_URL
  Tool API:       $TOOLAPI_URL
  Open the dashboard URL in a browser to use the RM cockpit.
$(printf '\033[1;36m=====================================================\033[0m')
EOF3
ok "Phase 6 complete."
log "Next: bash infra/phase7-guardrails/up.sh"
