server {
  listen 8080 default_server;
  listen [::]:8080 default_server;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /index.html { add_header Cache-Control "no-store, no-cache, must-revalidate"; expires 0; }
  location = /app.js     { add_header Cache-Control "no-store"; expires 0; }
  location = /ui.js      { add_header Cache-Control "no-store"; expires 0; }
  location = /ui.css     { add_header Cache-Control "no-store"; expires 0; }
  location = /rescue.js  { add_header Cache-Control "no-store"; expires 0; }
  location = /rescue.css { add_header Cache-Control "no-store"; expires 0; }
  location = /hni.js     { add_header Cache-Control "no-store"; expires 0; }
  location = /hni.css    { add_header Cache-Control "no-store"; expires 0; }
  location = /demo.js    { add_header Cache-Control "no-store"; expires 0; }
  location = /demo.css   { add_header Cache-Control "no-store"; expires 0; }
  location = / { try_files /index.html =404; }
  location / { try_files $uri $uri/ /index.html; }
  location = /healthz { add_header Content-Type application/json; return 200 '{"ok":true,"service":"contoso-msme-dashboard"}'; }
  location = /favicon.ico { log_not_found off; access_log off; return 204; }
}
