#!/usr/bin/env bash
# infra/common/prebuild_images.sh
#
# SPEED OPTIMIZATION — build all three container images CONCURRENTLY, up front.
#
# The Tool API (phase4), Video Assist (phase9) and CRM dashboard (phase6) images each
# only need the shared ACR from phase1 to build — they do NOT need phase2/AI Search.
# The deploy orchestrator launches this script in the BACKGROUND right after phase1 and
# lets it run while phase2 provisions AI Search (the ~10-minute long pole). By the time
# the deploy reaches phase4/6/9, the images are already in ACR, so those phases just
# deploy a ready image instead of building in series across later waves.
#
# Each image is tagged with a shared PREBUILD_TAG (deterministic, no ':latest' race) and
# also ':latest'. On success we record the exact image ref in prebuilt_images.env; the
# consuming phases source that file and reuse the ref. If a build FAILS (or this whole
# step is skipped), the marker var is simply absent and the phase falls back to building
# the image inline — so this optimization is always safe.
#
# All configuration comes from infra/common/env.sh — nothing here is hardcoded.
set -uo pipefail
PHASE="prebuild"; export PHASE
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=env.sh
source "$SCRIPT_DIR/env.sh"

log "Pre-build — building container images in parallel (overlaps phase2 AI Search)"
ensure_az_login

# ACR_LOGIN_SERVER comes from phase1 outputs; NAME_ACR from env.sh.
PHASE1_OUT="$SCRIPT_DIR/../phase1-platform/outputs.env"
[[ -f "$PHASE1_OUT" ]] || die "Phase 1 outputs missing: $PHASE1_OUT (run phase1 first)."
# shellcheck source=../phase1-platform/outputs.env
source "$PHASE1_OUT"
[[ -n "${ACR_LOGIN_SERVER:-}" && -n "${NAME_ACR:-}" ]] || die "Need ACR_LOGIN_SERVER + NAME_ACR to pre-build."

MARKER="$SCRIPT_DIR/prebuilt_images.env"
rm -f "$MARKER"

PREBUILD_TAG="v$(date -u +%Y%m%d%H%M%S)"
LOGDIR="${ACS_BUILD_LOGDIR:-/tmp/acs_build_logs}"
mkdir -p "$LOGDIR"

TOOLAPI_REF="${ACR_LOGIN_SERVER}/msme-toolapi:${PREBUILD_TAG}"
VIDEOASSIST_REF="${ACR_LOGIN_SERVER}/videoassist:${PREBUILD_TAG}"
DASHBOARD_REF="${ACR_LOGIN_SERVER}/msme-dashboard:${PREBUILD_TAG}"

log "Shared image tag: $PREBUILD_TAG"
log "  toolapi     -> $TOOLAPI_REF"
log "  videoassist -> $VIDEOASSIST_REF"
log "  dashboard   -> $DASHBOARD_REF"

# ---- Tool API (backend/Dockerfile, context = repo root) ----
( az acr build --registry "$NAME_ACR" \
    --image "msme-toolapi:${PREBUILD_TAG}" --image "msme-toolapi:latest" \
    --file "$REPO_ROOT/backend/Dockerfile" "$REPO_ROOT" --only-show-errors ) \
  >"$LOGDIR/prebuild-toolapi.log" 2>&1 &
PID_TOOLAPI=$!

# ---- Video Assist (videoassist/ context, its own Dockerfile) ----
( az acr build --registry "$NAME_ACR" \
    --image "videoassist:${PREBUILD_TAG}" --image "videoassist:latest" \
    "$REPO_ROOT/videoassist" --only-show-errors ) \
  >"$LOGDIR/prebuild-videoassist.log" 2>&1 &
PID_VA=$!

# ---- CRM dashboard (frontend-crm/Dockerfile; ACR-cache base, Docker Hub fallback) ----
( az acr build --registry "$NAME_ACR" \
      --image "msme-dashboard:${PREBUILD_TAG}" --image "msme-dashboard:latest" \
      --build-arg "BASE_REGISTRY=${ACR_LOGIN_SERVER}/" \
      --file "$REPO_ROOT/frontend-crm/Dockerfile" "$REPO_ROOT" --only-show-errors \
  || az acr build --registry "$NAME_ACR" \
      --image "msme-dashboard:${PREBUILD_TAG}" --image "msme-dashboard:latest" \
      --file "$REPO_ROOT/frontend-crm/Dockerfile" "$REPO_ROOT" --only-show-errors ) \
  >"$LOGDIR/prebuild-dashboard.log" 2>&1 &
PID_DASH=$!

# ---- Wait for all three, record only the images that built successfully ----
RC_TOOLAPI=0; RC_VA=0; RC_DASH=0
wait "$PID_TOOLAPI" || RC_TOOLAPI=$?
wait "$PID_VA"      || RC_VA=$?
wait "$PID_DASH"    || RC_DASH=$?

{
  echo "# Generated by infra/common/prebuild_images.sh on $(date -u --iso-8601=seconds)"
  echo "# Image refs for images pre-built in parallel. Consuming phases reuse these and"
  echo "# skip their inline 'az acr build'. A missing var => that phase builds inline."
  echo "export PREBUILD_TAG=\"$PREBUILD_TAG\""
  [[ "$RC_TOOLAPI" -eq 0 ]] && echo "export PREBUILT_TOOLAPI_IMAGE=\"$TOOLAPI_REF\""
  [[ "$RC_VA"      -eq 0 ]] && echo "export PREBUILT_VIDEOASSIST_IMAGE=\"$VIDEOASSIST_REF\""
  [[ "$RC_DASH"    -eq 0 ]] && echo "export PREBUILT_DASHBOARD_IMAGE=\"$DASHBOARD_REF\""
} > "$MARKER"

[[ "$RC_TOOLAPI" -eq 0 ]] && ok "Pre-built Tool API image"        || warn "Tool API pre-build failed (rc=$RC_TOOLAPI) — phase4 will build inline. See $LOGDIR/prebuild-toolapi.log"
[[ "$RC_VA"      -eq 0 ]] && ok "Pre-built Video Assist image"     || warn "Video Assist pre-build failed (rc=$RC_VA) — phase9 will build inline. See $LOGDIR/prebuild-videoassist.log"
[[ "$RC_DASH"    -eq 0 ]] && ok "Pre-built CRM dashboard image"    || warn "Dashboard pre-build failed (rc=$RC_DASH) — phase6 will build inline. See $LOGDIR/prebuild-dashboard.log"

if [[ "$RC_TOOLAPI" -eq 0 && "$RC_VA" -eq 0 && "$RC_DASH" -eq 0 ]]; then
  ok "All images pre-built. Marker: $MARKER"
  exit 0
fi
warn "Some images did not pre-build; those phases fall back to inline builds."
exit 0
