#!/usr/bin/env bash
# infra/phase5-rag/up.sh
#
# Phase 5 — RAG indexing + Tool API redeploy.
#   0. GUARD: docs/sop must contain the generated SOPs (run tools/generate first).
#   1. Install local indexing deps.
#   2. Create/update the AI Search index (idempotent).
#   3. Chunk + embed + upload SOPs.
#   4. Rebuild the Tool API image (now with rag.py + search.py) and update the app.
#   5. Smoke-test /v1/rag/retrieve.
set -euo pipefail
PHASE="phase5"; export PHASE
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../common/env.sh
source "$SCRIPT_DIR/../common/env.sh"

log "Phase 5 — RAG indexing + Tool API redeploy"
ensure_az_login
ensure_rg

# ---------- 0. GUARD: SOP corpus must exist ----------
SOP_DIR="$REPO_ROOT/docs/sop"
SOP_COUNT="$(find "$SOP_DIR" -maxdepth 1 -name '*.md' 2>/dev/null | wc -l | tr -d ' ')"
if [[ "$SOP_COUNT" == "0" ]]; then
  die "No SOPs found in $SOP_DIR. The RAG corpus (docs/sop/*.md) ships with this repo;
       ensure the docs/sop directory was included and is populated."
fi
ok "Found $SOP_COUNT SOP file(s) to index."

# ---------- Load earlier-phase outputs ----------
# phase4-toolapi is gone: the Tool API now runs on the phase10 VM behind Caddy at /api.
# phase10 (wave 3) still precedes phase5 (wave 4), and tools/deploy-toolapi-on-vm.sh runs
# inside that wave-3 block, so the API is already up and health-gated by the time we smoke
# test it here. The bearer no longer comes from a phase output at all — env.sh owns it.
PHASE1_OUT="$SCRIPT_DIR/../phase1-platform/outputs.env"
PHASE2_OUT="$SCRIPT_DIR/../phase2-ai/outputs.env"
PHASE10_OUT="$SCRIPT_DIR/../phase10-vmhost/outputs.env"
for f in "$PHASE1_OUT" "$PHASE2_OUT"; do
  [[ -f "$f" ]] || die "Missing $(basename "$(dirname "$f")") outputs: $f"
  # shellcheck disable=SC1090
  source "$f"
done
if [[ -f "$PHASE10_OUT" ]]; then
  # shellcheck disable=SC1090
  source "$PHASE10_OUT"
fi
ensure_toolapi_bearer
ok "Loaded outputs from phases 1, 2 and 10"

# ---------- 1. Local python deps ----------
log "Ensuring Python deps for indexer..."
python3 -m pip install --quiet --user \
  "azure-identity>=1.18.0" "azure-search-documents==11.5.1" "openai>=1.51.0" || \
  warn "pip install reported an issue; continuing if deps already present"
ok "Python deps ready"

# ---------- 2. Create/update index ----------
log "Creating/updating AI Search index ($SEARCH_INDEX_NAME)..."
SEARCH_ENDPOINT="$SEARCH_ENDPOINT" SEARCH_INDEX_NAME="$SEARCH_INDEX_NAME" \
  python3 "$SCRIPT_DIR/create_index.py"
ok "Index ready"

# ---------- 3. Index SOPs ----------
log "Chunking, embedding, and uploading SOPs..."
SEARCH_ENDPOINT="$SEARCH_ENDPOINT" \
SEARCH_INDEX_NAME="$SEARCH_INDEX_NAME" \
FOUNDRY_AOAI_ENDPOINT="$FOUNDRY_AOAI_ENDPOINT" \
FOUNDRY_EMBED_DEPLOYMENT="$FOUNDRY_EMBED_DEPLOYMENT" \
SOP_DIR="$SOP_DIR" \
  python3 "$SCRIPT_DIR/index_sops.py"
ok "SOPs indexed"

# ---------- 4. Smoke test ----------
# The old "(Optional) Rebuild Tool API image" step is GONE. PHASE5_REBUILD_TOOLAPI and
# TOOLAPI_IMAGE were ACR/Container-App concepts with no meaning now that the Tool API is a
# systemd service on the VM: the equivalent of a redeploy is simply re-running
# tools/deploy-toolapi-on-vm.sh. Nothing needed redeploying for RAG anyway — the backend
# reads the search index at runtime via managed identity.
TOKEN="${TOOLAPI_BEARER_TOKEN:-}"
[[ -n "$TOKEN" ]] || die "TOOLAPI_BEARER_TOKEN is unset (env.sh:ensure_toolapi_bearer should have set it)."
[[ -n "${TOOLAPI_URL:-}" ]] || die "TOOLAPI_URL is unset. Expected https://<host>/api from
infra/phase10-vmhost/outputs.env — run phase10 and tools/deploy-toolapi-on-vm.sh first."
log "Smoke test: $TOOLAPI_URL/v1/rag/retrieve"
RESP="$(curl -fsS -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
  -X POST "$TOOLAPI_URL/v1/rag/retrieve" \
  -d '{"query":"what documents are required before working capital renewal","top_k":3}' || echo '{"error":"curl_failed"}')"
echo "$RESP" | python3 -m json.tool 2>/dev/null || echo "$RESP"

cat > "$SCRIPT_DIR/outputs.env" <<EOF
# Generated by infra/phase5-rag/up.sh on $(date -u --iso-8601=seconds)
export RAG_INDEX_NAME="$SEARCH_INDEX_NAME"
EOF

cat <<EOF

$(printf '\033[1;36m================ Phase 5 — Deployed ================\033[0m')
Search index:                $SEARCH_INDEX_NAME  ($SEARCH_ENDPOINT)
SOPs indexed:                $SOP_COUNT file(s)
RAG endpoint:                $TOOLAPI_URL/v1/rag/retrieve
$(printf '\033[1;36m=====================================================\033[0m')
EOF
ok "Phase 5 complete."
log "Next: bash infra/phase10-vmhost/up.sh (if not already up) — there is no phase6."
