#!/usr/bin/env bash
# infra/phase5-rag/up.sh
#
# Phase 5 — RAG indexing + Tool API redeploy.
#   0. GUARD: docs/sop must contain the generated SOPs (run tools/generate first).
#   1. Install local indexing deps.
#   2. Create/update the AI Search index (idempotent).
#   3. Chunk + embed + upload SOPs.
#   4. Rebuild the Tool API image (now with rag.py + search.py) and update the app.
#   5. Smoke-test /v1/rag/retrieve.
set -euo pipefail
PHASE="phase5"; export PHASE
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../common/env.sh
source "$SCRIPT_DIR/../common/env.sh"

log "Phase 5 — RAG indexing + Tool API redeploy"
ensure_az_login
ensure_rg

# ---------- 0. GUARD: SOP corpus must exist ----------
SOP_DIR="$REPO_ROOT/docs/sop"
SOP_COUNT="$(find "$SOP_DIR" -maxdepth 1 -name '*.md' 2>/dev/null | wc -l | tr -d ' ')"
if [[ "$SOP_COUNT" == "0" ]]; then
  die "No SOPs found in $SOP_DIR. The RAG corpus (docs/sop/*.md) ships with this repo;
       ensure the docs/sop directory was included and is populated."
fi
ok "Found $SOP_COUNT SOP file(s) to index."

# ---------- Load earlier-phase outputs ----------
PHASE1_OUT="$SCRIPT_DIR/../phase1-platform/outputs.env"
PHASE2_OUT="$SCRIPT_DIR/../phase2-ai/outputs.env"
PHASE4_OUT="$SCRIPT_DIR/../phase4-toolapi/outputs.env"
for f in "$PHASE1_OUT" "$PHASE2_OUT" "$PHASE4_OUT"; do
  [[ -f "$f" ]] || die "Missing $(basename "$(dirname "$f")") outputs: $f"
  # shellcheck disable=SC1090
  source "$f"
done
ok "Loaded outputs from phases 1, 2, 4"

# ---------- 1. Local python deps ----------
log "Ensuring Python deps for indexer..."
python3 -m pip install --quiet --user \
  "azure-identity>=1.18.0" "azure-search-documents==11.5.1" "openai>=1.51.0" || \
  warn "pip install reported an issue; continuing if deps already present"
ok "Python deps ready"

# ---------- 2. Create/update index ----------
log "Creating/updating AI Search index ($SEARCH_INDEX_NAME)..."
SEARCH_ENDPOINT="$SEARCH_ENDPOINT" SEARCH_INDEX_NAME="$SEARCH_INDEX_NAME" \
  python3 "$SCRIPT_DIR/create_index.py"
ok "Index ready"

# ---------- 3. Index SOPs ----------
log "Chunking, embedding, and uploading SOPs..."
SEARCH_ENDPOINT="$SEARCH_ENDPOINT" \
SEARCH_INDEX_NAME="$SEARCH_INDEX_NAME" \
FOUNDRY_AOAI_ENDPOINT="$FOUNDRY_AOAI_ENDPOINT" \
FOUNDRY_EMBED_DEPLOYMENT="$FOUNDRY_EMBED_DEPLOYMENT" \
SOP_DIR="$SOP_DIR" \
  python3 "$SCRIPT_DIR/index_sops.py"
ok "SOPs indexed"

# ---------- 4. (Optional) Rebuild Tool API image ----------
# SKIPPED by default: the image phase4 already built from backend/ contains the RAG code
# (rag.py, search.py), and the Tool API reads the search index at runtime via managed
# identity — so nothing needs redeploying just to enable RAG. This avoids a full, redundant
# ~4-5 min image rebuild on every deploy. Set PHASE5_REBUILD_TOOLAPI=1 to force a
# rebuild+redeploy (e.g. after changing backend code between phase4 and phase5).
IMAGE_REPO="msme-toolapi"
if [[ "${PHASE5_REBUILD_TOOLAPI:-0}" == "1" ]]; then
  IMAGE_TAG="v$(date -u +%Y%m%d%H%M%S)"
  IMAGE_REF="${ACR_LOGIN_SERVER}/${IMAGE_REPO}:${IMAGE_TAG}"
  log "Rebuilding Tool API image with RAG: $IMAGE_REF"
  az acr build --registry "$NAME_ACR" \
    --image "${IMAGE_REPO}:${IMAGE_TAG}" --image "${IMAGE_REPO}:latest" \
    --file "$REPO_ROOT/backend/Dockerfile" "$REPO_ROOT" --only-show-errors
  ok "Image built"

  log "Updating Container App $NAME_CA_TOOLAPI ..."
  az containerapp update -g "$AZ_RG" -n "$NAME_CA_TOOLAPI" --image "$IMAGE_REF" --only-show-errors -o table
  ok "Container App updated"

  log "Waiting 12s for new revision..."
  sleep 12
else
  IMAGE_REF="${TOOLAPI_IMAGE:-reused-from-phase4}"
  ok "Skipping Tool API rebuild (PHASE5_REBUILD_TOOLAPI=0) — phase4 image already includes RAG code."
fi

# ---------- 5. Smoke test ----------
TOKEN="${TOOLAPI_BEARER_TOKEN:-}"
[[ -n "$TOKEN" ]] || die "TOOLAPI_BEARER_TOKEN missing from phase4 outputs.env (run phase4 first)."
log "Smoke test: /v1/rag/retrieve"
RESP="$(curl -fsS -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \
  -X POST "$TOOLAPI_URL/v1/rag/retrieve" \
  -d '{"query":"what documents are required before working capital renewal","top_k":3}' || echo '{"error":"curl_failed"}')"
echo "$RESP" | python3 -m json.tool 2>/dev/null || echo "$RESP"

cat > "$SCRIPT_DIR/outputs.env" <<EOF
# Generated by infra/phase5-rag/up.sh on $(date -u --iso-8601=seconds)
export RAG_INDEX_NAME="$SEARCH_INDEX_NAME"
export TOOLAPI_IMAGE_REF="$IMAGE_REF"
EOF

cat <<EOF

$(printf '\033[1;36m================ Phase 5 — Deployed ================\033[0m')
Search index:                $SEARCH_INDEX_NAME  ($SEARCH_ENDPOINT)
SOPs indexed:                $SOP_COUNT file(s)
Tool API image (updated):    $IMAGE_REF
RAG endpoint:                $TOOLAPI_URL/v1/rag/retrieve
$(printf '\033[1;36m=====================================================\033[0m')
EOF
ok "Phase 5 complete."
log "Next: bash infra/phase6-crm/up.sh"
