#!/usr/bin/env bash
# infra/persistent/up.sh
#
# Create the PERSISTENT layer: a never-wiped resource group holding a STATIC public IP.
# The IP anchors the stable hostname  rmassist.<ip>.nip.io  used by the committed
# Let's Encrypt certificate, so the cert survives full teardowns of the billable RG.
#
# Idempotent + one-time in spirit: run it ONCE (build_persistent.sh). Re-running converges
# and simply re-emits the same static IP.
set -euo pipefail
PHASE="persistent"; export PHASE

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common/env.sh
source "$SCRIPT_DIR/../common/env.sh"

log "Persistent layer — static public IP (nip.io anchor for the reusable Let's Encrypt cert)"

ensure_az_login
ensure_rg_persistent

DEPLOYMENT_NAME="persistent-$(date -u +%Y%m%d-%H%M%S)"
log "Deploying persistent Bicep (deployment: $DEPLOYMENT_NAME)..."
az deployment group create \
  --resource-group "$AZ_RG_PERSISTENT" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$SCRIPT_DIR/main.bicep" \
  --parameters \
      location="$AZ_REGION_PERSISTENT" \
      pipName="$NAME_PERSIST_PIP" \
      projectTag="$PROJECT_TAG_VALUE_PERSISTENT" \
  --only-show-errors \
  -o none \
  || die "Persistent Bicep deployment failed."

PERSIST_IP="$(persist_ip)"
[[ -n "$PERSIST_IP" ]] || die "Static IP not allocated — check the persistent deployment."
HOST="$(rmassist_host)"

OUTFILE="$SCRIPT_DIR/outputs.env"
cat > "$OUTFILE" <<EOF
# Generated by infra/persistent/up.sh on $(date -u --iso-8601=seconds)
export PERSIST_IP="$PERSIST_IP"
export PERSIST_PIP_ID="$(az network public-ip show -g "$AZ_RG_PERSISTENT" -n "$NAME_PERSIST_PIP" --query id -o tsv 2>/dev/null || true)"
export RMASSIST_HOST="$HOST"
EOF
ok "Outputs saved to $OUTFILE"

cat <<EOF

$(printf '\033[1;36m================ Persistent layer — ready ================\033[0m')
Persistent RG:      $AZ_RG_PERSISTENT   (NEVER deleted by wipe.sh)
Static public IP:   $PERSIST_IP  ($NAME_PERSIST_PIP)
Stable host:        $HOST
This host is the domain the Let's Encrypt cert is bound to. It is created ONCE and
reused across every rebuild — the billable VM (phase10) borrows this IP each build.
$(printf '\033[1;36m==========================================================\033[0m')
EOF
ok "Persistent layer complete."
