#!/usr/bin/env bash
# infra/phase1-platform/up.sh
#
# Phase 1 — Platform substrate.
# Deploys: Log Analytics, ACR, UAMI, Container Apps Environment, role assignments.
#
# Idempotent: re-running converges on the desired state (Bicep handles this).

set -euo pipefail
PHASE="phase1"
export PHASE

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common/env.sh
source "$SCRIPT_DIR/../common/env.sh"

log "Phase 1 — Platform substrate"

ensure_az_login
ensure_rg

# ---------- Resolve deployer identity (for ACR push role assignment) ----------
log "Resolving deployer identity..."
DEPLOYER_TYPE_RAW="$(az account show --query user.type -o tsv)"
case "$DEPLOYER_TYPE_RAW" in
  user) DEPLOYER_PRINCIPAL_TYPE="User" ;;
  servicePrincipal) DEPLOYER_PRINCIPAL_TYPE="ServicePrincipal" ;;
  *) die "Unsupported az account user type: $DEPLOYER_TYPE_RAW" ;;
esac

if [[ "$DEPLOYER_PRINCIPAL_TYPE" == "User" ]]; then
  DEPLOYER_OBJECT_ID="$(az ad signed-in-user show --query id -o tsv 2>/dev/null || true)"
else
  SP_APPID="$(az account show --query user.name -o tsv)"
  DEPLOYER_OBJECT_ID="$(az ad sp show --id "$SP_APPID" --query id -o tsv 2>/dev/null || true)"
fi

if [[ -z "${DEPLOYER_OBJECT_ID:-}" ]]; then
  die "Could not resolve deployer object ID. Check az login state."
fi
ok "Deployer: type=$DEPLOYER_PRINCIPAL_TYPE objectId=$DEPLOYER_OBJECT_ID"

# ---------- Deploy Bicep ----------
DEPLOYMENT_NAME="phase1-platform-$(date -u +%Y%m%d-%H%M%S)"
log "Deploying Bicep (deployment: $DEPLOYMENT_NAME)..."

az deployment group create \
  --resource-group "$AZ_RG" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$SCRIPT_DIR/main.bicep" \
  --parameters \
      location="$AZ_REGION" \
      suffix="$SUFFIX" \
      deployerObjectId="$DEPLOYER_OBJECT_ID" \
      deployerPrincipalType="$DEPLOYER_PRINCIPAL_TYPE" \
      projectTag="$PROJECT_TAG_VALUE" \
      lawName="$NAME_LAW" \
      acrName="$NAME_ACR" \
      uamiName="$NAME_UAMI" \
      caeName="$NAME_ACA_ENV" \
  --only-show-errors \
  -o table

ok "Bicep deployment succeeded."

# ---------- Capture outputs ----------
log "Capturing deployment outputs..."
OUTPUTS_JSON="$(az deployment group show \
  --resource-group "$AZ_RG" \
  --name "$DEPLOYMENT_NAME" \
  --query properties.outputs -o json)"

ACR_LOGIN_SERVER="$(echo "$OUTPUTS_JSON" | jq -r '.acrLoginServer.value')"
UAMI_PRINCIPAL_ID="$(echo "$OUTPUTS_JSON" | jq -r '.uamiPrincipalId.value')"
UAMI_CLIENT_ID="$(echo "$OUTPUTS_JSON" | jq -r '.uamiClientId.value')"
UAMI_ID="$(echo "$OUTPUTS_JSON" | jq -r '.uamiId.value')"
CAE_DEFAULT_DOMAIN="$(echo "$OUTPUTS_JSON" | jq -r '.caeDefaultDomain.value')"

# Persist outputs to a file other phases can source
OUTFILE="$SCRIPT_DIR/outputs.env"
cat > "$OUTFILE" <<EOF
# Generated by infra/phase1-platform/up.sh on $(date -u --iso-8601=seconds)
# Source this file from later phases to access Phase 1 outputs.
export ACR_LOGIN_SERVER="$ACR_LOGIN_SERVER"
export UAMI_PRINCIPAL_ID="$UAMI_PRINCIPAL_ID"
export UAMI_CLIENT_ID="$UAMI_CLIENT_ID"
export UAMI_ID="$UAMI_ID"
export CAE_DEFAULT_DOMAIN="$CAE_DEFAULT_DOMAIN"
EOF
ok "Outputs saved to $OUTFILE"

# ---------- Summary ----------
cat <<EOF

$(printf '\033[1;36m================ Phase 1 — Deployed ================\033[0m')
Log Analytics:               $NAME_LAW
ACR login server:            $ACR_LOGIN_SERVER
UAMI principal ID:           $UAMI_PRINCIPAL_ID
UAMI client ID (for env):    $UAMI_CLIENT_ID
ACA env default domain:      $CAE_DEFAULT_DOMAIN

Role assignments granted:
  - UAMI       -> ACR  (AcrPull)
  - You        -> ACR  (AcrPush)
$(printf '\033[1;36m=====================================================\033[0m')

EOF

ok "Phase 1 complete."
log "Next: bash infra/phase2-ai/up.sh"
