#!/usr/bin/env bash
# tools/deploy-videoassist-on-vm.sh
#
# Deploys the ACS Video Assist app (Node/Express + the Vite-built SPA) onto the phase10 VM
# as the native rmx-videoassist.service installed in Phase A. No container, no ACR.
#
# Reproduces the two-stage Dockerfile build natively:
#   stage 1  npm ci (FULL, including devDependencies) + npm run build
#            Vite, @azure/communication-calling, @azure/communication-common and the Speech
#            SDK are devDependencies and are required to BUNDLE the SPA. `npm ci --omit=dev`
#            first would fail the build with "Cannot find module 'vite'".
#   stage 2  npm prune --omit=dev
#            The browser SDKs are baked into dist/ by then and are dead weight at runtime;
#            the server only needs express + @azure/identity + @azure/communication-identity
#            + openai. Pruning is done AFTER a successful build and is skipped on failure so
#            a half-built tree is never left running.
#
# VA_BASE_PATH=/video/ is exported for the build so Vite emits asset URLs under the prefix.
# PUBLIC_BASE_PATH=/video goes into the runtime env so server.js injects window.__VA_BASE__
# for the fetch() paths Vite does not touch. See videoassist/vite.config.js for why the
# defaults are root-relative rather than /video.
#
# Transport is tar-over-ssh, matching deploy-toolapi-on-vm.sh and deploy-crm-on-vm.sh.
# Idempotent — safe to run on every build.
#
# Usage:  bash tools/deploy-videoassist-on-vm.sh
set -euo pipefail
PHASE="videoassist-vm"; export PHASE

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=../infra/common/env.sh
source "$REPO_ROOT/infra/common/env.sh"
cd "$REPO_ROOT"

# ---------- Prior-phase outputs ----------
PHASE10_OUT="$REPO_ROOT/infra/phase10-vmhost/outputs.env"
[[ -f "$PHASE10_OUT" ]] || die "VM outputs not found ($PHASE10_OUT). Run infra/phase10-vmhost/up.sh first."
# shellcheck disable=SC1090
source "$PHASE10_OUT"
[[ -n "${VM_HOST_IP:-}" && -n "${VM_SSH_KEY:-}" && -n "${VM_ADMIN_USER:-}" && -n "${RMASSIST_HOST:-}" ]] \
  || die "VM connection details missing from $PHASE10_OUT."

PHASE2_OUT="$REPO_ROOT/infra/phase2-ai/outputs.env"
[[ -f "$PHASE2_OUT" ]] || die "Phase 2 outputs missing: $PHASE2_OUT (run phase2 first)."
# shellcheck disable=SC1090
source "$PHASE2_OUT"

ensure_toolapi_bearer

SRC="$REPO_ROOT/videoassist"
[[ -f "$SRC/package.json" && -f "$SRC/server.js" ]] || die "Video Assist sources not found in $SRC."
[[ -f "$SRC/package-lock.json" ]] || die "package-lock.json missing — 'npm ci' requires it."

SSH_OPTS=(-i "$VM_SSH_KEY" -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null -o ConnectTimeout=15 -o LogLevel=ERROR)
vm_ssh()     { ssh -n "${SSH_OPTS[@]}" "${VM_ADMIN_USER}@${VM_HOST_IP}" "$@"; }
vm_pipe_in() { ssh "${SSH_OPTS[@]}" "${VM_ADMIN_USER}@${VM_HOST_IP}" "$@"; }

APP_DIR="${VM_VIDEOASSIST_DIR:-/opt/rmx/videoassist}"
APP_USER="${VM_APP_USER:-rmxapp}"
APP_ENV="${VM_VIDEOASSIST_ENV_FILE:-/opt/rmx/etc/videoassist.env}"
ORIGIN="https://${RMASSIST_HOST}"
BASE_PREFIX="${VIDEOASSIST_PATH_PREFIX:-/video}"
PUBLIC_URL="${ORIGIN}${BASE_PREFIX}"

log "Deploying Video Assist to $VM_HOST_IP:$APP_DIR ..."

# ---------- 1. Ship the sources ----------
vm_ssh "sudo mkdir -p $APP_DIR && sudo chown -R ${VM_ADMIN_USER}:${VM_ADMIN_USER} $APP_DIR" \
  || die "Could not prepare $APP_DIR on the VM."
# Drop stale source and build output, but KEEP node_modules so an unchanged dependency set
# does not have to be re-downloaded on every deploy (npm ci below still reconciles it).
vm_ssh "cd $APP_DIR && rm -rf client public data dist server.js nudge-engine.js toolapi.js teams.js graph.js insight-store.js vite.config.js package.json package-lock.json" || true

log "Shipping videoassist/ (excluding node_modules and dist) ..."
tar -C "$SRC" --exclude='node_modules' --exclude='dist' --exclude='.dockerignore' -czf - . \
  | vm_pipe_in "tar -C $APP_DIR -xzf -" \
  || die "Failed to ship videoassist/ to the VM."

# ---------- 2. Runtime config -> root-owned 0600 EnvironmentFile ----------
log "Writing $APP_ENV (root:root 0600) ..."
APP_ENV_LOCAL="$SCRIPT_DIR/.videoassist.env.rendered"
_shred_app_env() { [[ -f "$APP_ENV_LOCAL" ]] && { shred -u "$APP_ENV_LOCAL" 2>/dev/null || rm -f "$APP_ENV_LOCAL"; }; return 0; }
trap _shred_app_env EXIT
(
  umask 077
  {
    echo "# Contoso RM Assist Video Assist config. Generated by tools/deploy-videoassist-on-vm.sh."
    echo "# Root-owned 0600 systemd EnvironmentFile. DO NOT COMMIT."
    # Mounted under a path prefix: server.js injects this into every HTML response as
    # window.__VA_BASE__ so client fetch() paths resolve. Caddy strips it before Express.
    echo "PUBLIC_BASE_PATH=${BASE_PREFIX}"
    # Same origin now, so the cockpit deep links and CORS all point at one host.
    echo "CRM_BASE_URL=${ORIGIN}"
    echo "CRM_ALLOWED_ORIGIN=${ORIGIN}"
    echo "TOOLAPI_URL=${ORIGIN}${TOOLAPI_PATH_PREFIX:-/api}"
    echo "TOOLAPI_BEARER=${TOOLAPI_BEARER}"
    echo "FOUNDRY_ENDPOINT=${FOUNDRY_ENDPOINT:-}"
    echo "FOUNDRY_AOAI_ENDPOINT=${FOUNDRY_AOAI_ENDPOINT:-}"
    echo "VOICE_AI_CHAT_DEPLOYMENT=${VOICE_AI_CHAT_DEPLOYMENT:-}"
    echo "VOICE_AI_FAST_DEPLOYMENT=${VOICE_AI_FAST_DEPLOYMENT:-}"
    echo "VOICE_AI_REASONING_EFFORT=${VOICE_AI_REASONING_EFFORT:-low}"
    echo "VOICE_MODEL_ENABLED=${VOICE_MODEL_ENABLED:-1}"
    echo "SPEECH_REGION=${SPEECH_REGION:-}"
    echo "SPEECH_ENDPOINT=${SPEECH_ENDPOINT:-}"
    echo "SPEECH_RESOURCE_ID=${SPEECH_RESOURCE_ID:-}"
    echo "ACS_ENDPOINT=${ACS_ENDPOINT:-}"
    [[ -n "${RM_MEETING_URL:-}"      ]] && echo "RM_MEETING_URL=${RM_MEETING_URL}"
    [[ -n "${CALL_LEAD_SECONDS:-}"   ]] && echo "CALL_LEAD_SECONDS=${CALL_LEAD_SECONDS}"
    [[ -n "${SEARCH_ENDPOINT:-}"     ]] && echo "SEARCH_ENDPOINT=${SEARCH_ENDPOINT}"
    [[ -n "${SEARCH_INDEX_NAME:-}"   ]] && echo "SEARCH_INDEX_NAME=${SEARCH_INDEX_NAME}"
    # ACS_CONNECTION_STRING, TEAMS_*_WEBHOOK_URL, SCHEDULE_*_WEBHOOK_URL, GRAPH_* and
    # AZURE_CLIENT_ID all come from the SHARED /opt/rmx/etc/rmx.env written by phase10.
    true
  } > "$APP_ENV_LOCAL"
)
vm_ssh "sudo install -o root -g root -m 0600 /dev/null $APP_ENV" || die "Could not create $APP_ENV."
vm_pipe_in "sudo tee $APP_ENV >/dev/null" < "$APP_ENV_LOCAL" || die "Could not write $APP_ENV."
vm_ssh "sudo chmod 0600 $APP_ENV && sudo chown root:root $APP_ENV"
_shred_app_env

# ---------- 3. Install deps + build (stage 1), then prune (stage 2) ----------
log "Installing dependencies and building the SPA on the VM (this can take several minutes) ..."
vm_ssh "set -e
  cd $APP_DIR
  export npm_config_fund=false npm_config_audit=false
  # FULL install: Vite and the browser SDKs are devDependencies and the build needs them.
  npm ci
  # Vite reads VA_BASE_PATH (see vite.config.js) to prefix bundled asset URLs.
  VA_BASE_PATH='${BASE_PREFIX}/' npm run build
  test -f dist/index.html || { echo 'BUILD PRODUCED NO dist/index.html' >&2; exit 1; }
  # Only prune once the build has succeeded, so a failed build never leaves a tree that is
  # both unbuilt AND missing its build tooling.
  npm prune --omit=dev
" || die "npm ci / npm run build failed on the VM.
Re-run manually to see the full output:
  ssh ${VM_ADMIN_USER}@${VM_HOST_IP} 'cd $APP_DIR && npm ci && VA_BASE_PATH=${BASE_PREFIX}/ npm run build'"
ok "SPA built on the VM (dist/index.html present); dev dependencies pruned."

# Verify the prefix actually reached the bundled asset URLs. If this is wrong the page loads
# blank with 404s on /assets/... and nothing in the server logs explains why.
if ! vm_ssh "grep -q '${BASE_PREFIX}/assets/' $APP_DIR/dist/index.html"; then
  warn "dist/index.html does not reference ${BASE_PREFIX}/assets/ — Vite base may not have applied."
  vm_ssh "grep -oE '(src|href)=\"[^\"]+\"' $APP_DIR/dist/index.html | head -10" || true
  die "Vite base prefix missing from the built index.html. Expected asset URLs under ${BASE_PREFIX}/."
fi
ok "Bundled asset URLs carry the ${BASE_PREFIX}/ prefix."

# ---------- 4. Hand to the service user and start ----------
vm_ssh "sudo chown -R ${APP_USER}:${APP_USER} $APP_DIR" || die "Could not chown $APP_DIR to $APP_USER."
log "Starting rmx-videoassist.service ..."
vm_ssh "sudo systemctl daemon-reload && sudo systemctl enable rmx-videoassist.service >/dev/null 2>&1; sudo systemctl restart rmx-videoassist.service" \
  || die "Failed to start rmx-videoassist.service. Logs: ssh ${VM_ADMIN_USER}@${VM_HOST_IP} sudo journalctl -u rmx-videoassist -n 60"

# ---------- 5. Health check on the VM loopback first ----------
log "Health check on the VM loopback ..."
LOCAL_OK=0
for i in $(seq 1 30); do
  if vm_ssh "curl -fsS --max-time 5 http://${VIDEOASSIST_HOST:-127.0.0.1}:${VIDEOASSIST_PORT:-3000}/healthz >/dev/null 2>&1 || curl -fsS --max-time 5 http://${VIDEOASSIST_HOST:-127.0.0.1}:${VIDEOASSIST_PORT:-3000}/ >/dev/null 2>&1"; then
    LOCAL_OK=1; break
  fi
  sleep 4
done
if [[ "$LOCAL_OK" != "1" ]]; then
  warn "Video Assist is not answering on ${VIDEOASSIST_HOST:-127.0.0.1}:${VIDEOASSIST_PORT:-3000}. Recent logs:"
  vm_ssh 'sudo journalctl -u rmx-videoassist --no-pager -n 60' 2>/dev/null || true
  die "rmx-videoassist.service did not become healthy. This is the APP, not Caddy — check the
unit's ExecStart, that node_modules survived the prune, and that dist/ was built."
fi
ok "Video Assist healthy on the VM loopback."

# ---------- 6. Verify through Caddy, including the stripped prefix ----------
log "Verifying ${PUBLIC_URL}/ through Caddy ..."
GATE_OK=0
for i in $(seq 1 20); do
  if curl -fsS --max-time 10 --resolve "${RMASSIST_HOST}:443:${VM_HOST_IP}" "${PUBLIC_URL}/" >/dev/null 2>&1; then
    GATE_OK=1; break
  fi
  sleep 5
done
if [[ "$GATE_OK" != "1" ]]; then
  warn "Caddy did not serve ${PUBLIC_URL}/ although the app IS healthy on the VM loopback."
  vm_ssh 'sudo journalctl -u caddy --no-pager -n 40' 2>/dev/null || true
  die "Video Assist is not reachable through Caddy.
IF THIS FAILS, CHECK THE CADDY /video ROUTE IN /etc/caddy/Caddyfile — the '@video' handle or
its 'uri strip_prefix /video'. The app answered on 127.0.0.1:${VIDEOASSIST_PORT:-3000}. Verify:
  ssh ${VM_ADMIN_USER}@${VM_HOST_IP} sudo caddy validate --adapter caddyfile --config /etc/caddy/Caddyfile
  curl -sv --resolve ${RMASSIST_HOST}:443:${VM_HOST_IP} ${PUBLIC_URL}/"
fi
ok "Video Assist reachable at ${PUBLIC_URL}/"

# The served HTML must carry the injected base, or every client fetch() will hit the CRM
# webroot instead of the API and fail with a 404 that looks like a backend outage.
if ! curl -fsS --max-time 10 --resolve "${RMASSIST_HOST}:443:${VM_HOST_IP}" "${PUBLIC_URL}/" 2>/dev/null | grep -q "__VA_BASE__"; then
  warn "The served page does not contain the window.__VA_BASE__ injection."
  die "PUBLIC_BASE_PATH injection missing. server.js:sendHtml should insert
<script>window.__VA_BASE__=\"${BASE_PREFIX}\"</script> into every HTML response. Check that
PUBLIC_BASE_PATH is set in $APP_ENV and that the service was restarted."
fi
ok "window.__VA_BASE__ is injected into the served HTML."

# Both static sub-pages go through the same sendHtml path; check one end to end.
if curl -fsS --max-time 10 --resolve "${RMASSIST_HOST}:443:${VM_HOST_IP}" "${PUBLIC_URL}/schedule" >/dev/null 2>&1; then
  ok "Express sub-route ${PUBLIC_URL}/schedule resolves after prefix stripping."
else
  warn "${PUBLIC_URL}/schedule did not answer — check the Express route order in server.js."
fi

cat > "$REPO_ROOT/infra/phase10-vmhost/videoassist-outputs.env" <<EOF
# Generated by tools/deploy-videoassist-on-vm.sh on $(date -u --iso-8601=seconds)
export VIDEOASSIST_URL="$PUBLIC_URL"
EOF

ok "Video Assist deployed. Public base: $PUBLIC_URL"
log "Cockpit SSE stream: ${PUBLIC_URL}/insights/stream  (matches the @sse Caddy matcher)"
