// infra/phase4-toolapi/main.bicep
// Phase 4 — Tool API as a Container App (Contoso MSME RM Assist).
//
// References (pre-existing from earlier phases):
//   Container Apps Environment + ACR + UAMI (Phase 1); Foundry/Search/ACS wiring (Phase 2).
// Creates the Container App: UAMI attached, image pulled from ACR via AcrPull, all
// wiring values injected as literal Container App secrets (Key Vault-free), external
// HTTPS ingress on port 8000.

targetScope = 'resourceGroup'

@description('Azure region.')
param location string = resourceGroup().location

@description('Project tag.')
param projectTag string = 'contoso-retail-rm-assist-rakesh'

@description('Container Apps Environment name.')
param acaEnvName string

@description('ACR name (without .azurecr.io).')
param acrName string

@description('Container App name.')
param appName string

@description('Full image reference, e.g. acrmsmeXXXXX.azurecr.io/msme-toolapi:v1')
param imageRef string

@description('Resource ID of the UAMI.')
param uamiResourceId string

// ----- Secret values passed as literal Container App secrets (Key Vault-free) -----
@secure()
@description('Tool API bearer token (generated by phase4 up.sh).')
param toolapiBearerToken string
@secure()
@description('Azure AI Foundry services endpoint.')
param foundryEndpoint string
@secure()
@description('Azure AI Foundry OpenAI v1 endpoint.')
param foundryAoaiEndpoint string
@secure()
@description('Chat model deployment name.')
param foundryChatDeployment string
@secure()
@description('Embedding model deployment name.')
param foundryEmbedDeployment string
@secure()
@description('Voice Live model identifier.')
param foundryVoiceliveModel string
@secure()
@description('Voice Live realtime WSS endpoint.')
param foundryVoiceliveWsEndpoint string
@secure()
@description('AI Search endpoint.')
param searchEndpoint string
@secure()
@description('AI Search index name.')
param searchIndexName string
@secure()
@description('Azure Communication Services endpoint.')
param acsEndpoint string

@description('CORS origins as a comma-separated string.')
param corsOrigins string = '*'

@description('ACS caller number owned by ACS resource. Optional; can be supplied in UI.')
param acsCallerNumber string = ''

@description('Default RM phone number for ACS phone-call mode. Optional; can be supplied in UI.')
param acsDefaultRmPhone string = ''

@description('Default customer phone number for ACS phone-call mode. Optional; can be supplied in UI.')
param acsDefaultCustomerPhone string = ''

@description('External public base URL for Tool API callbacks. Leave blank to infer from request host.')
param acsPublicBaseUrl string = ''

@description('Locale for ACS real-time transcription.')
param acsTranscriptionLocale string = 'en-US'

@description('Enable intermediate ACS transcript events. Final-only is safer for nudge stability.')
param acsEnableIntermediateTranscripts string = 'false'

@description('Enable ACS audio-streaming to Azure Speech fallback when native ACS transcription is slow or unavailable.')
param acsEnableMediaSpeechFallback string = 'true'

@description('ACS transcript mode: media, native, both, or none. media is safest for the POC phone-call path.')
param acsTranscriptionMode string = 'media'

@description('Azure AI Services endpoint used by ACS transcription.')
param acsCognitiveServicesEndpoint string = ''

resource cae 'Microsoft.App/managedEnvironments@2024-03-01' existing = {
  name: acaEnvName
}
resource acr 'Microsoft.ContainerRegistry/registries@2023-11-01-preview' existing = {
  name: acrName
}

var commonTags = { project: projectTag, phase: 'phase4' }

resource app 'Microsoft.App/containerApps@2024-03-01' = {
  name: appName
  location: location
  tags: commonTags
  identity: {
    type: 'UserAssigned'
    userAssignedIdentities: {
      '${uamiResourceId}': {}
    }
  }
  properties: {
    managedEnvironmentId: cae.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 8000
        transport: 'auto'
        allowInsecure: false
        traffic: [ { latestRevision: true, weight: 100 } ]
      }
      registries: [
        { server: acr.properties.loginServer, identity: uamiResourceId }
      ]
      secrets: [
        { name: 'toolapi-bearer-token',          value: toolapiBearerToken }
        { name: 'foundry-endpoint',              value: foundryEndpoint }
        { name: 'foundry-aoai-endpoint',         value: foundryAoaiEndpoint }
        { name: 'foundry-chat-deployment',       value: foundryChatDeployment }
        { name: 'foundry-embed-deployment',      value: foundryEmbedDeployment }
        { name: 'foundry-voicelive-model',       value: foundryVoiceliveModel }
        { name: 'foundry-voicelive-ws-endpoint', value: foundryVoiceliveWsEndpoint }
        { name: 'search-endpoint',               value: searchEndpoint }
        { name: 'search-index-name',             value: searchIndexName }
        { name: 'acs-endpoint',                   value: acsEndpoint }
      ]
    }
    template: {
      containers: [
        {
          name: 'toolapi'
          image: imageRef
          resources: { cpu: json('0.5'), memory: '1Gi' }
          env: [
            { name: 'LOG_LEVEL', value: 'INFO' }
            { name: 'CORS_ORIGINS', value: corsOrigins }
            { name: 'DATA_DIR', value: '/app/data/csv' }
            { name: 'KB_DIR', value: '/app/data/knowledge_base' }
            { name: 'TOOLAPI_BEARER_TOKEN',          secretRef: 'toolapi-bearer-token' }
            { name: 'FOUNDRY_ENDPOINT',              secretRef: 'foundry-endpoint' }
            { name: 'FOUNDRY_AOAI_ENDPOINT',         secretRef: 'foundry-aoai-endpoint' }
            { name: 'FOUNDRY_CHAT_DEPLOYMENT',       secretRef: 'foundry-chat-deployment' }
            { name: 'FOUNDRY_EMBED_DEPLOYMENT',      secretRef: 'foundry-embed-deployment' }
            { name: 'FOUNDRY_VOICELIVE_MODEL',       secretRef: 'foundry-voicelive-model' }
            { name: 'FOUNDRY_VOICELIVE_WS_ENDPOINT', secretRef: 'foundry-voicelive-ws-endpoint' }
            { name: 'SEARCH_ENDPOINT',               secretRef: 'search-endpoint' }
            { name: 'SEARCH_INDEX_NAME',             secretRef: 'search-index-name' }
            { name: 'ACS_ENDPOINT',                  secretRef: 'acs-endpoint' }
            { name: 'ACS_CALLER_NUMBER',             value: acsCallerNumber }
            { name: 'ACS_DEFAULT_RM_PHONE',          value: acsDefaultRmPhone }
            { name: 'ACS_DEFAULT_CUSTOMER_PHONE',    value: acsDefaultCustomerPhone }
            { name: 'ACS_PUBLIC_BASE_URL',           value: acsPublicBaseUrl }
            { name: 'ACS_TRANSCRIPTION_LOCALE',      value: acsTranscriptionLocale }
            { name: 'ACS_ENABLE_INTERMEDIATE_TRANSCRIPTS', value: acsEnableIntermediateTranscripts }
            { name: 'ACS_COGNITIVE_SERVICES_ENDPOINT', value: acsCognitiveServicesEndpoint }
            { name: 'ACS_ENABLE_MEDIA_SPEECH_FALLBACK', value: acsEnableMediaSpeechFallback }
            { name: 'ACS_TRANSCRIPTION_MODE',        value: acsTranscriptionMode }
            { name: 'AZURE_CLIENT_ID', value: reference(uamiResourceId, '2023-01-31').clientId }
          ]
          probes: [
            { type: 'Liveness',  httpGet: { path: '/healthz', port: 8000 }, initialDelaySeconds: 5, periodSeconds: 30, failureThreshold: 3 }
            { type: 'Readiness', httpGet: { path: '/healthz', port: 8000 }, initialDelaySeconds: 3, periodSeconds: 10, failureThreshold: 3 }
          ]
        }
      ]
      // SCALE: pinned to a SINGLE replica on purpose.
      //
      // The Tool API keeps its runtime state in the FastAPI process — the store
      // is a per-process singleton (deps.py get_store -> app.state.store) and
      // backend/app/store.py holds `pending_writes`, `events` and
      // `call_records` as plain in-process lists with no shared backing store.
      //
      // The consent-gated CRM write is a TWO-CALL sequence: the caller POSTs
      // /v1/crm/update-candidate and then POSTs /v1/crm/approve-update with the
      // returned candidate_id (videoassist/server.js:565-566, and the cockpit's
      // own proposeTask()). With maxReplicas > 1 those two requests can land on
      // different replicas, and the approve then fails at
      // routes/analysis.py:371 with 404 "Candidate not found or already
      // processed" — so the case the customer just consented to is never
      // written. The same split-brain silently empties the post-call
      // transcripts panel (POST /call-records on one replica, GET on another)
      // and shows only a fraction of the glass-box audit trail.
      //
      // Scaling out would require moving that state to an external store, which
      // is out of scope for this demo; one replica also comfortably covers its
      // load.
      scale: { minReplicas: 1, maxReplicas: 1 }
    }
  }
}

output appFqdn string = app.properties.configuration.ingress.fqdn
output appUrl  string = 'https://${app.properties.configuration.ingress.fqdn}'
