#!/usr/bin/env bash
# infra/phase4-toolapi/up.sh
#
# Phase 4 — Tool API Container App.
#   1. Generate (or reuse) the Tool API bearer token — persisted in outputs.env, no Key Vault.
#   2. Build the image via `az acr build` (no local Docker).
#   3. Deploy the Container App via Bicep (secrets injected as literal Container App secrets).
#   4. Smoke-test /healthz and a bearer-protected route.
set -euo pipefail
PHASE="phase4"; export PHASE
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# shellcheck source=../common/env.sh
source "$SCRIPT_DIR/../common/env.sh"

log "Phase 4 — Tool API Container App"
ensure_az_login
ensure_rg

# ---------- Load Phase 1 outputs ----------
PHASE1_OUT="$SCRIPT_DIR/../phase1-platform/outputs.env"
[[ -f "$PHASE1_OUT" ]] || die "Phase 1 outputs missing: $PHASE1_OUT (run phase1 first)"
# shellcheck source=../phase1-platform/outputs.env
source "$PHASE1_OUT"
[[ -n "${UAMI_ID:-}" && -n "${ACR_LOGIN_SERVER:-}" ]] || die "Phase 1 outputs incomplete."
ok "Loaded Phase 1 outputs"

# ---------- Load Phase 2 outputs (Foundry/Search/ACS wiring — injected as literal secrets) ----------
PHASE2_OUT="$SCRIPT_DIR/../phase2-ai/outputs.env"
[[ -f "$PHASE2_OUT" ]] || die "Phase 2 outputs missing: $PHASE2_OUT (run phase2 first)"
# shellcheck source=../phase2-ai/outputs.env
source "$PHASE2_OUT"
[[ -n "${FOUNDRY_ENDPOINT:-}" && -n "${SEARCH_ENDPOINT:-}" && -n "${ACS_ENDPOINT:-}" ]] \
  || die "Phase 2 outputs incomplete (need FOUNDRY_ENDPOINT, SEARCH_ENDPOINT, ACS_ENDPOINT)."
ok "Loaded Phase 2 outputs (Foundry/Search/ACS wiring)"

# ---------- Tool API bearer token (Key Vault-free: persisted in this phase's outputs.env) ----------
# Reuse the existing token across re-runs so phase5/6/9 keep working; else generate one.
OUTFILE="$SCRIPT_DIR/outputs.env"
TOOLAPI_BEARER_TOKEN=""
if [[ -f "$OUTFILE" ]]; then
  # shellcheck disable=SC1090
  source "$OUTFILE"
fi
if [[ -n "${TOOLAPI_BEARER_TOKEN:-}" ]]; then
  ok "Reusing existing Tool API bearer token from $OUTFILE"
else
  TOOLAPI_BEARER_TOKEN="$(python3 -c 'import secrets; print(secrets.token_urlsafe(48))')"
  ok "Generated new Tool API bearer token"
fi

# ---------- Build image via ACR Tasks (or reuse a parallel pre-build) ----------
IMAGE_REPO="msme-toolapi"
PREBUILT_ENV="$SCRIPT_DIR/../common/prebuilt_images.env"
[[ -f "$PREBUILT_ENV" ]] && source "$PREBUILT_ENV"
if [[ -n "${PREBUILT_TOOLAPI_IMAGE:-}" ]]; then
  IMAGE_REF="$PREBUILT_TOOLAPI_IMAGE"
  ok "Reusing pre-built Tool API image (built in parallel during phase2): $IMAGE_REF"
else
  IMAGE_TAG="v$(date -u +%Y%m%d%H%M%S)"
  IMAGE_REF="${ACR_LOGIN_SERVER}/${IMAGE_REPO}:${IMAGE_TAG}"
  log "Building image via ACR: $IMAGE_REF"
  az acr build \
    --registry "$NAME_ACR" \
    --image "${IMAGE_REPO}:${IMAGE_TAG}" \
    --image "${IMAGE_REPO}:latest" \
    --file "$REPO_ROOT/backend/Dockerfile" \
    "$REPO_ROOT" \
    --only-show-errors
  ok "Image built."
fi

# ---------- Deploy Bicep ----------
DEPLOYMENT_NAME="phase4-toolapi-$(date -u +%Y%m%d-%H%M%S)"
log "Deploying Container App (deployment: $DEPLOYMENT_NAME)..."
az deployment group create \
  --resource-group "$AZ_RG" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$SCRIPT_DIR/main.bicep" \
  --parameters \
      location="$AZ_REGION" \
      projectTag="$PROJECT_TAG_VALUE" \
      acaEnvName="$NAME_ACA_ENV" \
      acrName="$NAME_ACR" \
      appName="$NAME_CA_TOOLAPI" \
      imageRef="$IMAGE_REF" \
      uamiResourceId="$UAMI_ID" \
      toolapiBearerToken="$TOOLAPI_BEARER_TOKEN" \
      foundryEndpoint="$FOUNDRY_ENDPOINT" \
      foundryAoaiEndpoint="$FOUNDRY_AOAI_ENDPOINT" \
      foundryChatDeployment="$FOUNDRY_CHAT_DEPLOYMENT" \
      foundryEmbedDeployment="$FOUNDRY_EMBED_DEPLOYMENT" \
      foundryVoiceliveModel="$VOICELIVE_MODEL" \
      foundryVoiceliveWsEndpoint="$VOICELIVE_WS_ENDPOINT" \
      searchEndpoint="$SEARCH_ENDPOINT" \
      searchIndexName="${SEARCH_INDEX_NAME:-contoso-retail-policy-index}" \
      acsEndpoint="$ACS_ENDPOINT" \
      corsOrigins="*" \
      acsCallerNumber="${ACS_CALLER_NUMBER:-}" \
      acsDefaultRmPhone="${ACS_DEFAULT_RM_PHONE:-}" \
      acsDefaultCustomerPhone="${ACS_DEFAULT_CUSTOMER_PHONE:-}" \
      acsPublicBaseUrl="${ACS_PUBLIC_BASE_URL:-}" \
      acsTranscriptionLocale="${ACS_TRANSCRIPTION_LOCALE:-en-US}" \
      acsEnableIntermediateTranscripts="${ACS_ENABLE_INTERMEDIATE_TRANSCRIPTS:-false}" \
      acsCognitiveServicesEndpoint="${ACS_COGNITIVE_SERVICES_ENDPOINT:-}" \
      acsEnableMediaSpeechFallback="${ACS_ENABLE_MEDIA_SPEECH_FALLBACK:-true}" \
      acsTranscriptionMode="${ACS_TRANSCRIPTION_MODE:-media}" \
  --only-show-errors -o table
ok "Container App deployed."

# ---------- Capture outputs ----------
OUTPUTS_JSON="$(az deployment group show -g "$AZ_RG" -n "$DEPLOYMENT_NAME" --query properties.outputs -o json)"
TOOLAPI_URL="$(echo "$OUTPUTS_JSON" | jq -r '.appUrl.value')"
cat > "$OUTFILE" <<EOF
# Generated by infra/phase4-toolapi/up.sh on $(date -u --iso-8601=seconds)
export TOOLAPI_URL="$TOOLAPI_URL"
export TOOLAPI_IMAGE="$IMAGE_REF"
export TOOLAPI_BEARER_TOKEN="$TOOLAPI_BEARER_TOKEN"
EOF
ok "Outputs saved (TOOLAPI_URL=$TOOLAPI_URL)"

# ---------- Smoke test ----------
log "Smoke-testing /healthz ..."
for i in $(seq 1 20); do
  if curl -fsS "$TOOLAPI_URL/healthz" >/dev/null 2>&1; then ok "Health OK"; break; fi
  [[ $i -eq 20 ]] && warn "Health check did not pass in time (app may still be starting)."
  sleep 6
done

BEARER="$TOOLAPI_BEARER_TOKEN"
log "Smoke-testing priority queue (bearer-protected) ..."
if curl -fsS -H "Authorization: Bearer $BEARER" "$TOOLAPI_URL/v1/portfolio/priority-queue" >/dev/null 2>&1; then
  ok "Priority queue endpoint responding."
else
  warn "Priority queue check failed (check logs: az containerapp logs show -g $AZ_RG -n $NAME_CA_TOOLAPI --tail 100)"
fi

log "Smoke-testing ACS config endpoint (bearer-protected) ..."
if curl -fsS -H "Authorization: Bearer $BEARER" "$TOOLAPI_URL/v1/acs/config" >/dev/null 2>&1; then
  ok "ACS config endpoint responding."
else
  warn "ACS config check failed (phone-call mode may still be starting)."
fi

cat <<EOF

$(printf '\033[1;36m================ Phase 4 — Deployed ================\033[0m')
  Tool API URL:   $TOOLAPI_URL
  Image:          $IMAGE_REF
  Bearer token:
  Try:  curl -H "Authorization: Bearer \$BEARER" $TOOLAPI_URL/v1/portfolio/priority-queue
$(printf '\033[1;36m=====================================================\033[0m')
EOF
ok "Phase 4 complete."
log "Next: bash infra/phase5-rag/up.sh"
